name: "UBDiag Upload"
description: "Build an Android app with gradle"
inputs:
  gradleTarget:
    description: "Gradle target"
    required: true
  gradleArgs:
    description: "Gradle arguments"
    required: true
runs:
  using: "docker"
  image: "docker://harbor.office.ubique.rocks/dockerhub-public-cache/cimg/android:2024.04.1"
  entrypoint: "./gradlew"
  args:
    - "${{ inputs.gradleTarget }}"
    - "${{ inputs.gradleArgs }}"
